### ISSUE TITLE
Nether and swamp

### ISSUE THREAD

**Issue by adikalon** [Atlante1952/Swamp#6]
It looks like the world of swamp is mixed with the world of nether. Add maximum depth setting for swamp

**Comment by Atlante1952** [comment]
oh ....

**Comment by atlante01** [comment]
I'll fix it now.

**Comment by Atlante1952** [comment]
Uhm it's weird:


`minetest.register_biome({
    name = "swamp",
    node_top = "swamp:dirt_with_swamp_grass",
    depth_top = 1,
    node_filler = "swamp:mud",
    depth_filler = 3,
    node_riverbed = "swamp:mud",
    depth_riverbed = 2,
    node_dungeon = "swamp:mud_brick",
    node_dungeon_alt = "swamp:mud_block",
    y_max = 10,
    y_min = -20,
    heat_point = 80,
    humidity_point = 98,
})
`

**Comment by Atlante1952** [comment]
I tried with the nether mod, and i saw nothing did you installed the most recent ?

**Comment by adikalon** [comment]
thank
